### ISSUE TITLE
clean_names() cannot transliterate accented characters anymore

### ISSUE THREAD

**Issue by nthun** [sfirke/janitor#299] opened 2019-05-15 15:31 UTC
I'm using janitor_1.2.0, and `clean_names()` seems to have stopped converting accented characters to latin ones in variable names. Previously, ő was converted to o, etc. You can see the current outcome in the replex below.

```r
> tibble::tibble(`aaü` = NA, `aaa` = NA) %>% 
    janitor::clean_names()
# A tibble: 1 x 2
  `aa�` aaa  
  <lgl> <lgl>
1 NA    NA   
Warning message:
In stri_length(string) :
  invalid UTF-8 byte sequence detected; try calling stri_enc_toutf8()
```

```r
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0   
```

**Comment by nthun** [comment] 2019-05-15 16:02
This is most probably an issue deriving from `make_clean_names()`. 

```r
> make_clean_names("qöaőűáóű")
[1] "q�aou��u"
Warning message:
In stri_length(string) :
  invalid UTF-8 byte sequence detected; try calling stri_enc_toutf8()
```
I see that `snakecase::to_any_case()` does the transliteration, which works for me just fine.

```r
> snakecase::to_any_case("qöaőűáóű", transliterations = "Latin-ASCII")
[1] "qoaouaou"
```

So until the function is corrected, `clean_names()` can be done like this:

```r
purrr::set_names(df, snakecase::to_any_case(names(df), transliterations = "Latin-ASCII"))
```

**Comment by sfirke** [comment] 2019-05-15 17:24
Interesting, thanks for reporting.  janitor has unit tests in place to ensure this transliteration succeeds across platforms and those checks are still passing. I can't reproduce your examples on my own machine, either.  For instance:
```
> make_clean_names("qöaőűáóű")
[1] "qoaouaou"
```
I'm running R 3.5.3 on this machine, Windows 10 x64.  I'm on stringi v1.4.3, what's your stringi version?

I don't see an immediate cause, but I'm also not very knowledgeable about encoding issues.

**Comment by sfirke** [comment] 2019-05-15 17:25
I don't get the warning in the first example that you do, maybe that's a clue.
```
> tibble::tibble(`aaü` = NA, `aaa` = NA) %>% 
+     janitor::clean_names()
# A tibble: 1 x 2
  aau   aaa  
  <lgl> <lgl>
1 NA    NA 
```

**Comment by sfirke** [comment] 2019-05-15 17:34
You could try reverting to janitor 1.1.1 (download [here](https://github.com/sfirke/janitor/releases/tag/1.1.1), install with devtools), and see if you get this behavior with everything else staying the same on your system?  That might be sufficient for confirming it as not a janitor issue, if that succeeds.

**Comment by nthun** [comment] 2019-05-17 09:05
The problem seems to persist on the earlier version, so it might be a compatibility issue. My stringi version is 1.4.3 btw.
I have no clue how, but is it possible that R 3.6.0 is responsible for this? When I was using 3.5.3, I didn't have this problem.

```r
> tibble::tibble(`aaü` = NA, `aaa` = NA) %>% 
+   janitor::clean_names()
# A tibble: 1 x 2
  `aa�` aaa  
  <lgl> <lgl>
1 NA    NA   
Warning message:
In stri_length(string) :
  invalid UTF-8 byte sequence detected; try calling stri_enc_toutf8()
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] janitor_1.1.1

loaded via a namespace (and not attached):
 [1] fansi_0.4.0      assertthat_0.2.1 zeallot_0.1.0    utf8_1.1.4       crayon_1.3.4    
 [6] backports_1.1.4  magrittr_1.5     pillar_1.4.0     cli_1.1.0        rlang_0.3.4     
[11] stringi_1.4.3    rstudioapi_0.10  snakecase_0.9.2  vctrs_0.1.0      tools_3.6.0     
[16] stringr_1.4.0    compiler_3.6.0   pkgconfig_2.0.2  tibble_2.1.1 
```

**Comment by nthun** [comment] 2019-05-17 09:09
I have just updated to snakecase_0.10.0, and the problem disappeared. So I guess you can close this.

**Comment by sfirke** [comment] 2019-05-17 15:01
huh.  Well, I'm glad it's working for you - sounds like a riddle.  I'll close this but feel free to share back if you ever pin down the specific cause for sure.

**Closed by sfirke** 2019-05-17 15:01 UTC
