### ISSUE TITLE
Feature Request: Round to a Fraction

### ISSUE THREAD

**Issue by billdenney** [sfirke/janitor#235] opened 2018-09-12 03:17 UTC
I often receive data from collaborators in Excel with values that look like `0.670000000000002` when they come into R (though with floating point math, this is a general issue).

I know that the values I'm looking at should be a multiple of 1/60 (since they are fractions of an hour), but it is painful to clean those numbers up manually.  I've recently started using the function below to assist with that cleaning, and I thought that it would be a good fit for `janitor`.

What do you think?

``` r
#' Round a value to a fraction, optionally then rounding to a number of digits.
#'
#' @param x The number to round
#' @param denominator The denominator of the fraction for rounding
#' @param digits The number of digits for rounding after rounding to the
#'   fraction (\code{Inf} indicates no subsequent rounding)
#' @return x rounded to a decimal value that has an integer numerator relative
#'   to \code{denominator} (possibly subsequently rounded to a number of decimal
#'   digits).
#' @export
round_to_fraction <- function(x, denominator, digits = Inf) {
  ret <- round(x * denominator, digits=0) / denominator
  if (!is.infinite(digits)) {
    ret <- round(ret, digits = digits)
  }
  ret
}
```

**Comment by sfirke** [comment] 2019-03-15 16:00
This is a cool idea and I know floating point issues are a vexing data cleaning problem especially for newer useRs.  I'll take a look at the PR but the above snippet looks pretty clear to me!

**Comment by sfirke** [comment] 2019-03-15 16:03
Real-world example: I made a tabyl last week and noted, "all values sum to 1 as they should, though to two values of 1, which I suspect is due to floating point precision errors:
![image](https://user-images.githubusercontent.com/7569808/54445011-50184380-471a-11e9-8052-da540b55d2ec.png)

When I compared these two `1` values with `==`, I get `FALSE` - but after running the function above with `denominator = 1` they are identical.  🌴

**Comment by sfirke** [comment] 2019-03-15 16:11
Is there any way this could more broadly address cases like mine above, where there's a trivial difference caused by floating point - either in terms of how the function is named or documented, or how it operates?  I think it nails the "should be a fraction with denominator X" case, but also has potential to be valuable in a host of other vexing floating point situations.

**Comment by billdenney** [comment] 2019-03-16 13:47
@sfirke, I thought I replied to this yesterday, but I guess not.

I think that the example you're looking at here is solved in one of two ways.  The simpler way is just with the `signif()` function.  A slightly more complex way would check if something were just off by a small amount and then round, but even with that, at some point you're still dealing with floating point numbers.

```r
> sprintf("%0.30f", signif(0.670000000000002, digits=20))
[1] "0.670000000000002038369473211787"
> sprintf("%0.30f", signif(0.670000000000002, digits=8))
[1] "0.670000000000000039968028886506"
> sprintf("%0.30f", signif(0.670000000000002, digits=3))
[1] "0.670000000000000039968028886506"
```

The best solution I can reasonably come up with would do something like:

```r
round_to_rel_tol <- function(x, tol=8, rel_tol=2) {
  mask_equal_round <-
    signif(x, digits=tol) == signif(x, digits=tol + rel_tol)
  x[mask_equal_round] <- signif(x[mask_equal_round], digits=tol)
  x
}
```

**Comment by sfirke** [comment] 2019-04-20 17:18
I will tinker with the documentation, then close this issue.  Thanks for the PR!

**Closed** 2019-04-20 18:10 UTC
