### ISSUE TITLE
`adorn_percentages` skips first column when denominator = "col"

### ISSUE THREAD

**Issue by daranzolin** [sfirke/janitor#304] opened 2019-06-07 18:33 UTC
E.g.:
```
library(tibble)
library(janitor)
library(magrittr)

tibble(x = c(10, 20), y = c(40, 50), z = c(100, 150)) %>%
 adorn_percentages(denominator = "col")

  x         y   z
 10 0.4444444 0.4
 20 0.5555556 0.6
```

```
tibble(x = c(10, 20), y = c(40, 50), z = c(100, 150)) %>% 
  select(-1) %>% 
  adorn_percentages(denominator = "col")

  y   z
 40 0.4
 50 0.6
```

**Comment by sfirke** [comment] 2019-06-09 16:41
This is intended behavior, the same thing happens with `adorn_percentages(denominator = "row")`.  The first sentence of `?adorn_percentages` states:

> This function excludes the first column of the input data.frame, assuming that it contains a descriptive variable. 

As to whether it _should_ work this way, that's another question and one that others have raised as well, so I'll close this as a duplicate of https://github.com/sfirke/janitor/issues/219.  See the discussion there of users being able to specify columns for the `adorn_` functions to operate on.

**Closed by sfirke** 2019-06-09 16:41 UTC
