### ISSUE TITLE
clean_names doesn't affect the delta symbol on OS X

### ISSUE THREAD

**Issue by seyounger** [sfirke/janitor#204] opened 2018-05-31 13:14 UTC
On Windows clean_names() replaces the 'δ' symbol with 'd' but on OS X it is unaffected.

```r
library(janitor)

dat <- structure(list(`Sample ID` = "sample 1", `δ2H, in ‰` = -24.99), row.names = c(NA, 
                                                                                     -1L), class = c("tbl_df", "tbl", "data.frame"))
clean_names(dat)
```

**Comment by sfirke** [comment] 2018-05-31 17:56
Thanks for submitting this.  I think this discrepancy would come from the function `to_any_case` from snakecase.

@Tazinho, do you experience the above behavior (I can confirm that it gets transliterated to `d` on Windows) and do you either understand what would be causing the cross-platform difference or know how to address it?

**Comment by sfirke** [comment] 2018-05-31 18:03
Hrm.  I'm trying to create a test for this and noticed that when I run your code above on Windows, I can't even get the delta character to be the name of the column:
```
> names(dat)
[1] "Sample ID" "d2H, in ‰"
```
^^^ that's _without_ running `clean_names()`.  Could it be that the lowercase delta just prints as a d on Windows?

**Comment by seyounger** [comment] 2018-05-31 18:37
Ah, my example wasn't good. I'm getting the issue when reading excel files with the delta symbol in the column name. Haven't found a good way to make a reprex reading an .xlsx file, but here's a file.

https://github.com/seyounger/example_data/blob/master/clean_names_delta_issue.xlsx

```r
library(readxl)

dat <- read_excel('clean_names_delta_issue.xlsx')

library(janitor)

#dat <- structure(list(`Sample ID` = "sample 1", `δ2H, in ‰` = -24.99), row.names = c(NA, 
#                                                                                     -1L), class = c("tbl_df", "tbl", "data.frame"))
names(dat)
clean_names(dat)
names(dat)
```

**Comment by sfirke** [comment] 2018-05-31 18:57
Thanks, now I can replicate this change (delta -> d) on Windows.  I found a [StackOverflow Post](https://stackoverflow.com/a/28494252/4470365) that describes Windows-specific encoding problems.  Though in this case I think my preferred behavior would be for delta to become d, with identical behavior across platforms also being a priority.

I don't know much (certainly not what I should) about encoding.  Malte, or anyone else, do you have an idea for how `clean_names()` could uniformly make this conversion across platforms?

**Comment by Tazinho** [comment] 2018-05-31 20:12
I tried to recreate the issue in a clean packrat project on Windows 10 (I can also test on Ubuntu when neede later).
For me the delta stays as delta. My guess is that the behaviour depends on the OS and/or the encoding.

However, the issue should be resolved in **stringi** since basically `to_any_case()` calls
```
> stringi::stri_trans_general(names(dat), id = "Latin-ASCII")
[1] "Sample ID" "δ2H, in ‰"
```
@sfirke I assumed it's best to file an issue at stringi and wait here till it's resolved!?

**Comment by Tazinho** [comment] 2018-05-31 21:10
As mentioned in the stringi issue by @gagolews one quick way to fix it would be to chain the operations `"Greek-Latin"` and "Latin-ASCII" as a new default for `clean_names()` within `the to_any_case()`-part. In **stringi** this is done via semicolon and in **snakecase** via providing a character vector.

> snakecase::to_any_case(input_string, transliterations = c("Greek-Latin", "Latin-ASCII"))
[1] "d_2_h_in"
> snakecase::to_any_case(input_string, transliterations = c("Latin-ASCII"))
[1] "δ_2_h_in"

**Comment by billdenney** [comment] 2018-11-30 19:46
I'm having a similar issue with the Greek mu symbol in a name ("µ"); my issue isn't necessarily a cross-platform issue, but a usability issue.

Might it help to have a simplification option to transliterate all characters to ASCII prior to conversion?  That could occur with something like the following:

```r
> iconv("µ", to="ASCII//TRANSLIT")
[1] "?"
> iconv("δ", to="ASCII//TRANSLIT")
[1] "d"
```

It could be as simple as replacing this:
```r
  new_names <- old_names %>%
    gsub("'", "", .) %>% # remove single quotation marks
```

with

```r
  new_names <- old_names %>%
    iconv(to="ASCII//TRANSLIT") %>%
    gsub("'", "", .) %>% # remove single quotation marks
```

here: https://github.com/sfirke/janitor/blob/4bf8ddfc9b1bb1bd43e794431db021bf0010cba0/R/make_clean_names.R#L49-L50

More complex which would allow backward compatibility would be to add an option called something like `ascii_only` through the `clean_names` family of functions.

**Closed** 2020-03-12 03:25 UTC
