### ISSUE TITLE
adorn_totals to certain rows or columns

### ISSUE THREAD

**Issue by jmerone** [sfirke/janitor#219] opened 2018-07-21 00:10 UTC
Hi Sam,

I've really enjoyed using your package. Is it possible to modify the ```adorn_totals()``` function to specify either the column(s) or row(s) from which to compute the total?

```r
library(janitor)
library(dplyr)

some_df <- data.frame( drug = rep(c('A','B', 'C'), 2),
                                       year =  rep(c(2016, 2017), 3),
                                        patients = sample(5:100, 6))

some_df %>%
   adorn_totals("row")
```

This finds the total of patients but also inadvertently adds the total of year.

 | drug |  year | patients |
| --- | --- | --- |
  |   A  |2016   |      16 |
|     B  | 2017        | 13|
  |   C |  2016 |         77|
 |    A | 2017  |       32 |
|     B  | 2016  |    53 |
 |    C  | 2017  |    100 |
| Total | 12099   |     291|

Similarly,

 ```r
some_df2 <- data.frame( locationA = sample(1:100, 5), locationB = sample(1:100, 5),
 locationC = sample(1:100,5))

some_df2 %>%
adorn_totals("col")
```
This adds up the totals in locationB and locationC but not from locationA. 

| locationA | locationB| locationC | Total |
| --- | --- | --- | --- |
|        26   |     76   |     63   | 139 |
 |       59   |     66    |    93   |159 |
 |       10    |    73     |   98  |  171 |
  |      43     |   80      |  70  | 150 |
   |     14      |  10      |   4    | 14 |

**Comment by sfirke** [comment] 2018-08-25 18:28
I appreciate you opening this issue.  The root cause is similar to #231, that the `adorn_` functions could use an overhaul to work better with non-tabyl inputs (I built them solely around tabyls, with a few concessions to general usage where I could).

I could see a future where the `adorn_` functions take a specification of column names, built on `dplyr::select` so that you can use all of the select helpers.  That would be part of a big overhaul, I think.  Given that a few people have opened issues like this one, it might be merited.  If adding the option to `select` columns, how else might we change the `adorn_`s for general usage?

I suspect that's the real way to address what you're pointing out.  But some more specific comments on this case:

- A workaround in the meantime is to cast columns you don't want to get totalled as character class.  That will exclude them from getting totalled.  You could do that with `mutate_at`.
- In the bottom case, you could add a dummy column, move it to the first position with `everything()` in `select`, add the totals, and drop the dummy.  Crude but would work.
- I don't expect we'd get to specifying rows, data.frames don't lend themselves well to row identifiers.  Specifying columns, yes.

**Comment by AlvaroPica** [comment] 2018-11-14 09:20
Thanks Sam for the packages.

I would also like to have this feature added to adorn_!

Best!.

**Comment by StephieLaPugh** [comment] 2019-01-26 15:41
Thanks so much for this package. 

Another vote for column-specific adorn_totals! Example: I work in a legal consulting field and we often have to present things as schedules of payments, like interest on a damages award. I've built a script to pull various interest rates and compounding periods and run a full set of quarterly/annually compounded payments by period. 

Begin | End | Beginning Balance | Interest Rate | Interest | Ending Balance

At the bottom, I need a total row with just the total for the "Interest" column. 

Adorn_total is currently the ONLY function I've been able to find in any package that even comes close to letting me do this, which is the only think keeping me locked in Excelhell on this type of report. 

Thanks again! This package is a lifesaver!

**Comment by sfirke** [comment] 2019-07-11 01:45
This could apply to `clean_names` too.  Someone has a rough implementation in this tweet: https://twitter.com/Benjaming_G/status/1141467717674733568

**Comment by sfirke** [comment] 2020-03-20 18:28
This is in progress on another branch: https://github.com/sfirke/janitor/tree/tidyselect_adorns I'm more than halfway through, I think, though adding tests for the new functionality may turn up unexpected problems.

**Comment by sfirke** [comment] 2020-04-04 20:39
Alright these are fixed on the master branch!  Check it out using the examples from the top of this page:

```
library(dplyr)
some_df <- data.frame( drug = rep(c('A','B', 'C'), 2),
                                       year =  rep(c(2016, 2017), 3),
                                        patients = sample(5:100, 6))
some_df %>%
  adorn_totals("row",,,, -year) # Exempts year column
```

And for the other example:
```
some_df2 <- data.frame( locationA = sample(1:100, 5), locationB = sample(1:100, 5),
locationC = sample(1:100,5))

some_df2 %>%
  adorn_totals(,,,,contains("location"))
```

**Closed by sfirke** 2020-04-04 20:39 UTC
Labels: in progress
