### ISSUE TITLE
adorn_percentages("col") after adorn_totals("col") does not work 

### ISSUE THREAD

**Issue by arhot** [sfirke/janitor#525] opened 2023-02-02 09:09 UTC
Previously working code to get both per-column % and total % is broken, including the example from here https://sfirke.github.io/janitor/articles/tabyls.html

```r
set.seed(1)
raw_data <- data.frame(sex = rep(c("m", "f"), 3000),
                       age = round(runif(3000, 1, 102), 0))
raw_data$agegroup = cut(raw_data$age, quantile(raw_data$age, c(0, 1/3, 2/3, 1)))

comparison <- raw_data %>%
  tabyl(agegroup, sex, show_missing_levels = F) %>%
  adorn_totals(c("row", "col")) %>%
  adorn_percentages("col") %>%
  adorn_pct_formatting(digits = 1)
```
Results in erroring out with "Error in FUN(X[[i]], ...) : only defined on a data frame with all numeric-alike variables" 
Not adding a total column before adorning percentages fixes it.

It is a call to a non-janitor function that fails, so it could plausibly be a package issue (setdiff()?) so I can share session info if need be, but I figured I'd let you know and see if you can reproduce it.

**Comment by sfirke** [comment] 2023-02-02 12:00
Sorry about this. It's fixed on main branch, try installing the latest
janitor from GitHub. I am in the process of submitting to CRAN now.

Duplicate of #490. See
https://github.com/sfirke/janitor/issues/490#issuecomment-1286958910.

**Comment by arhot** [comment] 2023-02-02 12:51
Great, thanks, sorry about the spam! I looked at open issues but didn't think it would be in process, looking forward to the new version!

**Comment by sfirke** [comment] 2023-02-02 17:04
Whew janitor 2.2.0 is on CRAN now.  Try installing it like normal and see if this resolves 😁 Thanks for reporting!

**Closed by sfirke** 2023-02-02 17:04 UTC
