### ISSUE TITLE
Two-way tabyl and n totals row or column

### ISSUE THREAD

**Issue by korailR** [sfirke/janitor#391] opened 2020-07-22 23:40 UTC
In a two-way tabyl, it lacks the possibility to display only the n totals row or column (from which the percentages are calculated) as the cprop function of the questionr package does.

**Comment by sfirke** [comment] 2020-07-25 18:35
Closing this as a duplicate of #313 where I explored this at great length.  If this is a different question, please clarify.

**Closed by sfirke** 2020-07-25 18:35 UTC
Labels: duplicate
