### ISSUE TITLE
different default updates to clean_names

### ISSUE THREAD

**Issue by amartinNPS** [sfirke/janitor#135] opened 2017-09-25 15:26 UTC
👋 

Very cool to see the `snakecase` integration!

I would like to suggest that clean_names have a different `case` argument by default.  While I like snakecase, I _believe_ that old janitor `cleannames()` produced something closer to lowercamel.

I have a bunch of code like

```
      test_stateid = sid_check_stateid(stateidentificationnumber),
      test_firstname = sid_check_firstname(firstname),
      test_lastname = sid_check_lastname(lastname),
```

that just broke because I updated janitor, and output of clean_names now defaults to `state_identification_number`.

guessing that anyone else with `clean_names` in their pipeline would see the same thing; in this case I would argue that the default behavior should prioritize consistency with prior releases even if there is a preference for snakecase on the development team here.

thoughts?  If there is agreement I will submit the PR!

**Comment by sfirke** [comment] 2017-09-25 15:45
I'm glad you filed this issue - I did not expect/intend for this to be a breaking change.  What is the input string that went from `stateidentificationnumber` to `state_identification_number`?  The prior version of janitor would turn `"a test variable name"` into `"a_test_variable_name"`.

**Comment by almartin82** [comment] 2017-09-25 17:09
I (believe) that the prior version of janitor turned
`LocalIdentificationNumber` (in the csv) into `localidentificationnumber`
(in R).

Now I am seeing `LocalIdentificationNumber` become
`local_identification_number` - and the only thing that happened (again, to
the best that I can determine) is that I updated janitor.

**Comment by sfirke** [comment] 2017-09-25 17:23
Ah okay, I can reproduce that as the fault of the janitor update.  Sorry for the breakage.  Camel case variable names in the raw data are now detected and that spacing is preserved via underscores.

This is tricky, since the old `clean_names` behavior doesn't map neatly to any of the new cases.  Before, `"LocalNumber"` became `"localnumber"` and `"Local Number"` became `"local_number"`; under the new options, these would both map to `"local_number"` (`case = "snake"`) or `"localNumber"` (`case = "small_camel"`).

I think this consistency is an improvement in janitor ... but I see how this will be a massively breaking change.  I will ponder that tradeoff and welcome feedback from anyone interested.

One option would be to offer another case option, `"old_janitor"`; then to deal with the breakage, you could find and replace `clean_names()` with `clean_names(case ="old_janitor")` instead of having to manually address the changed variable names.  Still a breaking change, but maybe this softens the impact?

**Comment by rgknight** [comment] 2017-09-25 20:41
I like the new behavior as the going forward option, but also feel bad
about a breaking change like this. Haven't been following the snake case
implementation, but it would be nice if you could set your preferred
conversation method once per session as an option, instead of with each
call. Would make the transition easier and would be useful more broadly.
Some of the logging packages may have ideas on how to do that. Maybe look
at https://github.com/smbache/loggr/blob/master/R/log_file.R

**Comment by almartin82** [comment] 2017-09-26 01:49
`case = old_janitor()` sounds ideal! should I hack at an implementation or
do you have an idea about how to implement?

**Comment by sfirke** [comment] 2017-09-26 10:53
That would be swell if you took a crack at this.  My first idea for implementation is to retain a snapshot of the old clean_names() function from before #131 was merged.  Maybe as a separate internal function `clean_names_v030` and/or anonymously within the new clean_names().  Then say, if `case == "old_janitor"`, call that legacy function, otherwise proceed as is.

Anyone see problems with that approach and/or a better one?

**Comment by Tazinho** [comment] 2017-09-26 12:10
I can think of three options:

1. new case in janitor: case = `old_janitor`, like already suggested (advantage: no breaking code)
2. recommend a workaround: use "stringr::str_to_lower()" or "base::tolower" in front of invoking `clean_names()`, like: `iris %>% purrr::set_names(base::tolower(names(iris))) %>% janitor::clean_names()`
3. giving `clean_names()` the `postprocess` argument from `snakecasae::to_any_case()`, as shown below. So it is possible to swich from snakecase, i.e. `clean_names(string, case = "snake")` to allowercase `clean_names(string, case = string, postprocess = "")`. The advantage is, that it is vectorised, so it is also possible to mix snakecase and allowercase: `clean_names(string, case = "snake", postprocess = c("_", "", "_"))`. The latter will convert first and last to snakecase and the second to alllowercase. `clean_names()` would become more flexible in general, however, it still involves a bit extra work for those users, which are affected by the last update and also (rare) edgecases like this mixed one "Local_IdentificationNumber" will still not be handled like in the old version.

```r
library(snakecase)
library(magrittr)

clean_names <- function(dat, case = "snake", postprocess = NULL){
  
  # Takes a data.frame, returns the same data frame with cleaned names
  old_names <- names(dat)
  new_names <- old_names %>%
    gsub("'", "", .) %>% # remove single quotation marks
    gsub("\"", "", .) %>% # remove double quotation marks
    gsub("%", ".percent_", .) %>% # starting with "." as a workaround, to make
    # ".percent" a valid name. The "." will be replaced in the call to to_any_case
    # via the preprocess argument anyway.
    gsub("^[ ]+", "", .) %>% # remove leading spaces
    make.names(.) %>%
    # Handle dots, multiple underscores, case conversion, string transliteration
    snakecase::to_any_case(case = case, preprocess = "\\.", 
                           replace_special_characters = c("Latin-ASCII"),
                           postprocess = postprocess)
  
  # Handle duplicated names - they mess up dplyr pipelines
  # This appends the column number to repeated instances of duplicate variable names
  dupe_count <- vapply(1:length(new_names), function(i) { 
    sum(new_names[i] == new_names[1:i]) }, integer(1))
  
  new_names[dupe_count > 1] <- paste(new_names[dupe_count > 1],
                                     dupe_count[dupe_count > 1],
                                     sep = "_")
  stats::setNames(dat, new_names)
}

>df <- data.frame(LocalIdentificationNumber = 1)
clean_names(df)
#  local_identification_number
# 1                           1
clean_names(df, postprocess = "")
#  localidentificationnumber
# 1                         1
```

**Comment by sfirke** [comment] 2017-09-26 12:53
Thanks for adding your ideas, Malte.  A consideration with option 2 is that in addition to the case changes, which `tolower()` would address, we made other minor changes to `clean_names`, namely how letters like like `œ` are handled (and how the % sign is handled).  Adding `tolower` would fix most of the breaking but in (probably uncommon) cases where there's a variable name like `"farœ"` it will get cleaned to `faroe` which would still be a breaking change.

**Comment by sfirke** [comment] 2017-10-01 19:19
@almartin82 do you want to send a PR implementing an argument `case = "old_janitor"` that calls the `clean_names()` function as written in the current CRAN version, 0.3.0?  You must be busy with the little one, thought I'd check in case you implemented this already to keep your own work afloat.

**Comment by sfirke** [comment] 2017-10-11 18:51
This is fairly high priority, as I'm getting feedback from other users of the dev version that their stuff broke, too.  Let me know if anyone is working on this (hacktoberfest!), otherwise I'll prioritize it soon.  I'm adding a temporary fix to my first comment above so that others see it.

**Comment by sfirke** [comment] 2017-10-13 19:41
This is closed by #139.  Fix is to specify `case = "old_janitor"` - users will need to find instances of `clean_names` in their code and add that argument. - @almartin82, if you have any scripts you haven't already implemented workarounds on, see if this helps?

**Closed by sfirke** 2017-10-13 19:41 UTC
Labels: hacktoberfest

**Comment by sfirke** [comment] 2018-02-09 17:18
ha thought of this thread ... b/c I eat my own dogfood, I am fixing up an old script now that broke due to changes to clean_names that I merged in last night.  Glad all the improvements are happening in one big release, and I hope that's the last breaking change to `clean_names()`.

**Comment by almartin82** [comment] 2018-02-10 03:15
😁😁
